version: '3'

services:
  api: 
    build:
      context: .
      dockerfile: Dockerfile
    image: gems-api
    container_name: gems-api-container
    ports:
      - 8000:8000
    volumes:
      - .:/app