const adminUsers = [
    {
        firstname: 'Ghana',
        lastname: 'Police',
        email: 'ghanapolice@gems.gh',
        username: 'Ghana Police',
        password: 'adminpassword1',
        contact: 191,
        role: 'admin',
        affiliate: 'Ghana Police Service',
    },
    {
        firstname: 'Ghana',
        lastname: 'Fire',
        email: 'ghanafire@gems.gh',
        username: 'Ghana Fire',
        password: 'ghanafire2*23',
        contact: 192,
        role: 'admin',
        affiliate: 'Ghana Fire Service',
    },
    {
        firstname: 'Ghana',
        lastname: 'Ambulance',
        email: 'ghanaambulance@gems.gh',
        username: 'Ghana Ambulance',
        password: 'ghanaambulance2*23',
        contact: 193,
        role: 'admin',
        affiliate: 'Ghana Ambulance Service',
    },
    {
        firstname: 'Ghana',
        lastname: 'Electricity',
        email: 'ghanaecg@gems.gh',
        username: 'ECG',
        password: 'ghanaecg2*23',
        contact: 302611611,
        role: 'admin',
        affiliate: 'Electricity Company of Ghana',
    },
    {
        firstname: 'Local',
        lastname: 'Assembly',
        email: 'ghanalocal@gems.gh',
        username: 'Local Assembly',
        password: 'ghanalocal2*23',
        contact: 100,
        role: 'admin',
        affiliate: 'Local Assembly',

    },
];

module.exports = adminUsers